### ISSUE TITLE
Scalability of NanoRepeat 

### ISSUE THREAD

**Issue by 18parkky** [WGLab/NanoRepeat#14]
Hello, I'm trying to measure the scalability of NanoRepeat by using varying number of cores, but is constantly obtaining roughly the same runtime, regardless of how many cores I use.

Here is some information about my input data:
- ONT (R9.4.1)
- mean coverage 50x 
- 200 STR region

The command I used is: `nanoRepeat.py -i _my_bam_-t bam -r _my_reference_ -b _my_STR_bed_ -c _num_cores_ -o _output_dir_ --ploidy 1`

Could it be that my data is too small to observe the scalability of NanoRepeat?
Thanks for reading!

Best regards,
18parkky

**Comment by fangli80** [comment]
Hello 18parkky,
This is because only the alignment step is multi-threaded. If your repeat length (total length) is small, the alignment step finishes very quickly. Other steps such as analysis of alignment results, plotting figures, and input/output files are not parallelized.

A solution to this is to process multiple repeat regions at the same time. I can modify NanoRepeat to improve multi-threading performance. 

Thanks!
Li
